name: Simple Announcer
version: '${project.version}'
main: de.sesosas.simpleproject.SimpleAnnouncer
commands:
  sa-reload:
    description: Reload the config
    permission: sa.reload
    permission-message: §cYou are not allowed to use this command!
