name: SimpleAnnouncer
version: '1.0'
main: de.sesosas.simpleproject.simpleannouncer.SimpleAnnouncer
softdepend: [PlaceholderAPI]
commands:
  sa-reload:
    description: Reload the config
    permission: sa.reload
    permission-message: §cYou are not allowed to use this command!
